
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CUsuario = new javax.swing.JMenuItem();
        CGenero = new javax.swing.JMenuItem();
        CAutor = new javax.swing.JMenuItem();
        CObra = new javax.swing.JMenuItem();
        CAutoria = new javax.swing.JMenuItem();
        CEditora = new javax.swing.JMenuItem();
        CLivro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MLocacao = new javax.swing.JMenuItem();
        MDevolucao = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ConLivro = new javax.swing.JMenuItem();
        ConLocacao = new javax.swing.JMenuItem();
        ConUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca");

        jMenu1.setText("Cadastro");

        CUsuario.setText("Usuário");
        CUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(CUsuario);

        CGenero.setText("Gênero");
        CGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGeneroActionPerformed(evt);
            }
        });
        jMenu1.add(CGenero);

        CAutor.setText("Autor");
        CAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAutorActionPerformed(evt);
            }
        });
        jMenu1.add(CAutor);

        CObra.setText("Obra");
        CObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CObraActionPerformed(evt);
            }
        });
        jMenu1.add(CObra);

        CAutoria.setText("Autoria");
        CAutoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAutoriaActionPerformed(evt);
            }
        });
        jMenu1.add(CAutoria);

        CEditora.setText("Editora");
        CEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEditoraActionPerformed(evt);
            }
        });
        jMenu1.add(CEditora);

        CLivro.setText("Livro");
        CLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLivroActionPerformed(evt);
            }
        });
        jMenu1.add(CLivro);
        jMenu1.add(jSeparator1);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu1.add(Sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        MLocacao.setText("Locação");
        MLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLocacaoActionPerformed(evt);
            }
        });
        jMenu2.add(MLocacao);

        MDevolucao.setText("Devolução");
        MDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDevolucaoActionPerformed(evt);
            }
        });
        jMenu2.add(MDevolucao);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");

        ConLivro.setText("Livro");
        ConLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConLivroActionPerformed(evt);
            }
        });
        jMenu3.add(ConLivro);

        ConLocacao.setText("Locação");
        ConLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConLocacaoActionPerformed(evt);
            }
        });
        jMenu3.add(ConLocacao);

        ConUsuario.setText("Usuário");
        ConUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(ConUsuario);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void CAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAutorActionPerformed
        CadastroAutor tela = new CadastroAutor();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);

    }//GEN-LAST:event_CAutorActionPerformed

    private void CUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUsuarioActionPerformed
        CadastroUsuario tela = new CadastroUsuario();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_CUsuarioActionPerformed

    private void CGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGeneroActionPerformed
        CadastroGenero tela = new CadastroGenero();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_CGeneroActionPerformed

    private void CObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CObraActionPerformed
        CadastroObra tela = new CadastroObra();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_CObraActionPerformed

    private void CAutoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAutoriaActionPerformed
        CadastroAutoria tela = new CadastroAutoria();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_CAutoriaActionPerformed

    private void CEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEditoraActionPerformed
        CadastroEditora tela = new CadastroEditora();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_CEditoraActionPerformed

    private void CLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLivroActionPerformed
        CadastroLivro tela = new CadastroLivro();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_CLivroActionPerformed

    private void MLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLocacaoActionPerformed
        MovLocacao tela = new MovLocacao();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MLocacaoActionPerformed

    private void MDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDevolucaoActionPerformed
        MovDevolucao tela = new MovDevolucao();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MDevolucaoActionPerformed

    private void ConLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConLivroActionPerformed
        ConsultaLivro tela = new ConsultaLivro();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_ConLivroActionPerformed

    private void ConLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConLocacaoActionPerformed
        ConsultaLocacao tela = new ConsultaLocacao();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_ConLocacaoActionPerformed

    private void ConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConUsuarioActionPerformed
        ConsultaUsuario tela = new ConsultaUsuario();
        tela.setLocationRelativeTo(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_ConUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CAutor;
    private javax.swing.JMenuItem CAutoria;
    private javax.swing.JMenuItem CEditora;
    private javax.swing.JMenuItem CGenero;
    private javax.swing.JMenuItem CLivro;
    private javax.swing.JMenuItem CObra;
    private javax.swing.JMenuItem CUsuario;
    private javax.swing.JMenuItem ConLivro;
    private javax.swing.JMenuItem ConLocacao;
    private javax.swing.JMenuItem ConUsuario;
    private javax.swing.JMenuItem MDevolucao;
    private javax.swing.JMenuItem MLocacao;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
