
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class MovDevolucao extends javax.swing.JFrame {

    BeanDiversos dv = new BeanDiversos();
    private DefaultTableModel tabModel;

    /**
     * Creates new form MovDevolucao
     */
    public MovDevolucao() {
        dv.passaCamposComEnter(this);
        initComponents();
        this.tabModel = (DefaultTableModel) tabDevolucao.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        Devolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDevolucao = new javax.swing.JTable();
        Sair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolução");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Código");

        codigoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoUsuarioFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Usuário");

        Devolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Devolver.setText("Devolver");
        Devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverActionPerformed(evt);
            }
        });

        tabDevolucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabDevolucao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tabDevolucao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Livro", "Data", "Devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabDevolucao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabDevolucao);
        if (tabDevolucao.getColumnModel().getColumnCount() > 0) {
            tabDevolucao.getColumnModel().getColumn(0).setResizable(false);
            tabDevolucao.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabDevolucao.getColumnModel().getColumn(1).setResizable(false);
            tabDevolucao.getColumnModel().getColumn(2).setResizable(false);
            tabDevolucao.getColumnModel().getColumn(3).setResizable(false);
        }

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/User.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Sair))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Devolver)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Devolver)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoUsuarioFocusLost

        try {
            dv.Conexao();
            dv.sttm = dv.con.prepareStatement("Select nome from usuario where matricula = ?");
            dv.sttm.setString(1, codigoUsuario.getText());
            ResultSet rs = dv.sttm.executeQuery();

            if (rs.next()) {
                nome.setText(dv.RetString(rs.getString("nome"), "C"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                dv.con.close();
            } catch (Exception ex) {
            }
        }

        SelecionarDevolucao();
    }//GEN-LAST:event_codigoUsuarioFocusLost

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void codigoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoUsuarioFocusGained
        codigoUsuario.setText("");
        nome.setText("");
    }//GEN-LAST:event_codigoUsuarioFocusGained

    private void DevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverActionPerformed

        int linha = tabDevolucao.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Para devolver um livro primeiro digite um código e escolha o livro que queseja devolver na tabela!");
        } else {
            int resp = 0;
            try {
                dv.Conexao();
                resp = JOptionPane.showConfirmDialog(null, "Confirma Devolução dessa Obra?");
                if (resp == 0) {
                    dv.sttm = dv.con.prepareStatement("update movimentacao set data_devolucao = ? where matricula = ? and nr_livro = ?");
                    dv.sttm.setString(1, dv.ConvData(dv.DataSistema()));
                    dv.sttm.setString(2, codigoUsuario.getText());
                    dv.sttm.setString(3, tabModel.getValueAt(linha, 0).toString());
                    dv.sttm.executeUpdate();
                }
                dv.con.commit();
            } catch (Exception e) {
                try {
                    dv.con.rollback();
                    e.printStackTrace();
                } catch (SQLException ex) {
                }
            } finally {
                try {
                    dv.con.close();
                } catch (Exception ex) {
                }
            }
        }
        SelecionarDevolucao();

    }//GEN-LAST:event_DevolverActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        codigoUsuario.setText("");
        nome.setText("");
    }//GEN-LAST:event_formFocusGained
    public void SelecionarDevolucao() {
        tabModel.setRowCount(0);
        try {
            dv.Conexao();
            dv.sttm = dv.con.prepareStatement("Select M.data_devolucao, M.matricula,L.nr_livro,O.titulo,M.data_emprestimo,M.data_prevista from livro L, obra O, movimentacao M Where (L.nr_obra = O.nr_obra) and (M.nr_livro = L.nr_livro) and M.matricula=? and m.data_devolucao IS NULL order by M.data_emprestimo, O.titulo");
            dv.sttm.setString(1, codigoUsuario.getText());

            ResultSet rs = dv.sttm.executeQuery();
            while (rs.next()) {
                String[] linha = new String[]{rs.getString("nr_livro"), rs.getString("titulo"), dv.RetString(rs.getString("data_emprestimo"),"D"), dv.RetString(rs.getString("data_prevista"),"D")};
                tabModel.addRow(linha);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                dv.con.close();
            } catch (Exception ex) {
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovDevolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Devolver;
    private javax.swing.JButton Sair;
    private javax.swing.JTextField codigoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTable tabDevolucao;
    // End of variables declaration//GEN-END:variables
}
